server:
    mode: debug
    name: epik-explorer
    http_port: 3002
    log_dir: ./log

badgerdb:
    tipset: ./db/tipset
    power: ./db/power
    message: ./db/message

epik:
    rpc_host: ws://18.181.234.52:1234/rpc/v0
    rpc_token: 
    main_privatekey: 
